/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoirer;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PCexpress
 */
public class equipes extends javax.swing.JFrame {
     public static Connection cnx =DBConnexion.ConnectBD();
    PreparedStatement prepared=null;
    ResultSet resultat=null;
    int test=0;
     
    /**
     * Creates new form equipes
     */
    public equipes() {
        initComponents();
        setLocationRelativeTo(null);
        ChekID();
        refresh();
    }
    public void refresh(){
    Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT * FROM `équipe` WHERE 1");
    ResultSet rs=pr.executeQuery();
    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex)
    {
    Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    public void ChekID(){
        Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT `Numequipe` FROM `équipe` WHERE 1");
    ResultSet rs=pr.executeQuery();
    while(rs.next()){
        String ID=rs.getString("Numequipe");
        String id=TFNumequipe.getText();
        if(ID.equals(id)){
            JOptionPane.showMessageDialog(null,"ce équpie est dans les données");
            test=test+1;
        }else{
            
        }
    }
    }catch(SQLException e){
        e.printStackTrace();
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAjoutre = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnModifer = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnValid = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNumequipe = new javax.swing.JLabel();
        jLabelNomequipe = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        TFNumequipe = new javax.swing.JTextField();
        TFNomequipe = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TFrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        CBrech = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        btnAjoutre.setBackground(new java.awt.Color(64, 43, 100));
        btnAjoutre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjoutreMousePressed(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnAjoutreLayout = new javax.swing.GroupLayout(btnAjoutre);
        btnAjoutre.setLayout(btnAjoutreLayout);
        btnAjoutreLayout.setHorizontalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btnAjoutreLayout.setVerticalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnModifer.setBackground(new java.awt.Color(64, 43, 100));
        btnModifer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModiferMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModiferMousePressed(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnModiferLayout = new javax.swing.GroupLayout(btnModifer);
        btnModifer.setLayout(btnModiferLayout);
        btnModiferLayout.setHorizontalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnModiferLayout.setVerticalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSupprimer.setBackground(new java.awt.Color(64, 43, 100));
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupprimerMousePressed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupprimerLayout = new javax.swing.GroupLayout(btnSupprimer);
        btnSupprimer.setLayout(btnSupprimerLayout);
        btnSupprimerLayout.setHorizontalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSupprimerLayout.setVerticalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnImprime.setBackground(new java.awt.Color(64, 43, 100));
        btnImprime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimeMousePressed(evt);
            }
        });

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_print_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnImprimeLayout = new javax.swing.GroupLayout(btnImprime);
        btnImprime.setLayout(btnImprimeLayout);
        btnImprimeLayout.setHorizontalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnImprimeLayout.setVerticalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        btnValid.setBackground(new java.awt.Color(64, 43, 100));
        btnValid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValidMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValidMousePressed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_view_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnValidLayout = new javax.swing.GroupLayout(btnValid);
        btnValid.setLayout(btnValidLayout);
        btnValidLayout.setHorizontalGroup(
            btnValidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnValidLayout.setVerticalGroup(
            btnValidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValidLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reply_all_arrow_55px.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjoutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModifer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnImprime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnAjoutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_g_50px.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_d_50px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_q_50px_2.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_u_50px.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_p_50px.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_50px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(60, 60, 60)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1060, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumequipe.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabelNumequipe.setText("Num équipe");
        jPanel4.add(jLabelNumequipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 106, 40));

        jLabelNomequipe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNomequipe.setText("Nom équipe");
        jPanel4.add(jLabelNomequipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 106, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, 10));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 490, 20));

        TFNumequipe.setBackground(new java.awt.Color(242, 242, 242));
        TFNumequipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNumequipeKeyPressed(evt);
            }
        });
        jPanel4.add(TFNumequipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 40));

        TFNomequipe.setBackground(new java.awt.Color(242, 242, 242));
        TFNomequipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNomequipeKeyPressed(evt);
            }
        });
        jPanel4.add(TFNomequipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 490, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 1060, 170));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 1060, 240));
        jPanel1.add(TFrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 370, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_50px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 120, 90, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setText("recherche par catégoie:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 50));

        CBrech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N_équipe", "Nom" }));
        jPanel1.add(CBrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnAjoutreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMousePressed
        // TODO add your handling code here:
        setcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValid);
    }//GEN-LAST:event_btnAjoutreMousePressed

    private void btnModiferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMousePressed
        // TODO add your handling code here:
        setcolor(btnModifer);
        resetcolor(btnAjoutre);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValid);
    }//GEN-LAST:event_btnModiferMousePressed

    private void btnSupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMousePressed
        // TODO add your handling code here:
        setcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnImprime);
        resetcolor(btnValid);
    }//GEN-LAST:event_btnSupprimerMousePressed

    private void btnImprimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMousePressed
        // TODO add your handling code here:
         setcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnValid);
    }//GEN-LAST:event_btnImprimeMousePressed

    private void btnValidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidMousePressed
        // TODO add your handling code here:
        setcolor(btnValid);
        resetcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
    }//GEN-LAST:event_btnValidMousePressed

    private void btnValidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidMouseClicked
        // TODO add your handling code here:
        TFNumequipe.setText("");
        TFNomequipe.setText("");
    }//GEN-LAST:event_btnValidMouseClicked

    private void btnModiferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMouseClicked
        // TODO add your handling code here:
        String m=TFNumequipe.getText();
        String n=TFNomequipe.getText();
        
       
         if (n.equals(""))
        {
         JOptionPane.showMessageDialog(null,"champ vid","Error",JOptionPane.ERROR_MESSAGE);
        }
         String sql="UPDATE `équipe` SET `Nom`=? WHERE  `Numequipe`="+TFNumequipe.getText()+"";
        
        try{
        prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
          
            prepared.setString(1, n);
            prepared.execute();
            refresh();
        }catch(SQLException e){
          System.out.println(e);
        }         
    }//GEN-LAST:event_btnModiferMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
        String m=TFNumequipe.getText();
        try{
        String sql="DELETE FROM `équipe` WHERE `équipe`.`Numequipe`= "+TFNumequipe.getText()+"";
       int cho  = JOptionPane.showConfirmDialog(null,"Êtes-vous sûr de vouloir supprimer");
       if(  cho == JOptionPane.YES_OPTION) {
           prepared=(PreparedStatement) Login.cnx.prepareStatement(sql);
           prepared.execute();
           System.out.println("Supprimer avec succès");
       } else {
       }
        refresh();
        
        }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         int rowIndex=jTable2.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        TFNumequipe.setText(model.getValueAt(rowIndex, 0).toString());
        TFNomequipe.setText(model.getValueAt(rowIndex, 1).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(TFrech.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else 
            
            if(CBrech.getSelectedItem().equals("N_équipe")){
               try{
                    PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Numequipe`, `Nom` FROM `équipe` WHERE `Numequipe`="+TFrech.getText()+"");
                    ResultSet rs=pr.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(SQLException ex)
                        {
                        Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                        }
                     }else 
                            if(CBrech.getSelectedItem().equals("Nom")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Numequipe`, `Nom`  FROM `équipe` WHERE `Nom`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }
                                
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAjoutreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMouseClicked
        // TODO add your handling code here:
         ChekID(); 
        String m=TFNumequipe.getText();
        String n=TFNomequipe.getText();
        try {
        String sql="INSERT INTO `équipe`(`Numequipe`, `Nom`) VALUES (?,?)";
        
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, m);
            prepared.setString(2, n);
            prepared.execute();
            refresh();
            
          
          System.out.println("ajouter avec succès");
          }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnAjoutreMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        WindowDirecteur CP = new WindowDirecteur();
                    CP.show();
                    dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void TFNumequipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNumequipeKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        { TFNumequipe.setEditable(false);
         jLabelNumequipe.setForeground(Color.red);
        }else{
             TFNumequipe.setEditable(true);
             jLabelNumequipe.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFNumequipeKeyPressed

    private void TFNomequipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNomequipeKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFNomequipe.setEditable(true);
         jLabelNomequipe.setForeground(Color.black);
        }else{
              TFNomequipe.setEditable(false);
             jLabelNomequipe.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFNomequipeKeyPressed
     void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equipes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrech;
    private javax.swing.JTextField TFNomequipe;
    private javax.swing.JTextField TFNumequipe;
    private javax.swing.JTextField TFrech;
    private javax.swing.JPanel btnAjoutre;
    private javax.swing.JPanel btnImprime;
    private javax.swing.JPanel btnModifer;
    private javax.swing.JPanel btnSupprimer;
    private javax.swing.JPanel btnValid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomequipe;
    private javax.swing.JLabel jLabelNumequipe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
