/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoirer;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static laboratoirer.equipes.cnx;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PCexpress
 */
public class materiels extends javax.swing.JFrame {
  public static Connection cnx =DBConnexion.ConnectBD();
    PreparedStatement prepared=null;
    ResultSet resultat=null;
    int test=0;
    /**
     * Creates new form materiels
     */
    public materiels() {
        initComponents();
        setLocationRelativeTo(null);
         ChekID();
        refresh();
    }
     public void refresh(){
    Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT * FROM `matérial` WHERE 1");
    ResultSet rs=pr.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex)
    {
    Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    public void ChekID(){
        Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT `Nummatérial` FROM `matérial` WHERE 1");
    ResultSet rs=pr.executeQuery();
    while(rs.next()){
        String ID=rs.getString("Nummatérial");
        String id=TFNumMateriel.getText();
        if(ID.equals(id)){
            JOptionPane.showMessageDialog(null,"ce projet est dans les données");
            test=test+1;
        }else{
            
        }
    }
    }catch(SQLException e){
        e.printStackTrace();
    
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAjoutre = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnModifer = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnValide = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNumMAT = new javax.swing.JLabel();
        jLabelNomMT = new javax.swing.JLabel();
        jLabelTYMT = new javax.swing.JLabel();
        jLabelCarcMT = new javax.swing.JLabel();
        TFNumMateriel = new javax.swing.JTextField();
        TFNomMateriel = new javax.swing.JTextField();
        TFCaracteristiquemateriel = new javax.swing.JTextField();
        TFTypeMateriel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TFrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        CBrech = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        btnAjoutre.setBackground(new java.awt.Color(64, 43, 100));
        btnAjoutre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutre.setPreferredSize(new java.awt.Dimension(122, 75));
        btnAjoutre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjoutreMousePressed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnAjoutreLayout = new javax.swing.GroupLayout(btnAjoutre);
        btnAjoutre.setLayout(btnAjoutreLayout);
        btnAjoutreLayout.setHorizontalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnAjoutreLayout.setVerticalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnModifer.setBackground(new java.awt.Color(64, 43, 100));
        btnModifer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModiferMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModiferMousePressed(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnModiferLayout = new javax.swing.GroupLayout(btnModifer);
        btnModifer.setLayout(btnModiferLayout);
        btnModiferLayout.setHorizontalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnModiferLayout.setVerticalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSupprimer.setBackground(new java.awt.Color(64, 43, 100));
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.setPreferredSize(new java.awt.Dimension(122, 75));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupprimerMousePressed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupprimerLayout = new javax.swing.GroupLayout(btnSupprimer);
        btnSupprimer.setLayout(btnSupprimerLayout);
        btnSupprimerLayout.setHorizontalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSupprimerLayout.setVerticalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnImprime.setBackground(new java.awt.Color(64, 43, 100));
        btnImprime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprime.setPreferredSize(new java.awt.Dimension(122, 75));
        btnImprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimeMousePressed(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_print_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnImprimeLayout = new javax.swing.GroupLayout(btnImprime);
        btnImprime.setLayout(btnImprimeLayout);
        btnImprimeLayout.setHorizontalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnImprimeLayout.setVerticalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnValide.setBackground(new java.awt.Color(64, 43, 100));
        btnValide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValide.setPreferredSize(new java.awt.Dimension(122, 75));
        btnValide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValideMousePressed(evt);
            }
        });

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_view_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnValideLayout = new javax.swing.GroupLayout(btnValide);
        btnValide.setLayout(btnValideLayout);
        btnValideLayout.setHorizontalGroup(
            btnValideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnValideLayout.setVerticalGroup(
            btnValideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reply_all_arrow_55px.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjoutre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnModifer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnImprime, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnValide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAjoutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnValide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_g_50px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 41, 88));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 6, 44, 88));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, 44, 88));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 6, 44, 88));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 6, 41, 88));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 6, 39, 88));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 6, 41, 88));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_d_50px.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 6, 38, 88));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 6, 41, 88));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 6, 39, 88));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_m_50px.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 6, -1, 88));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_a_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 6, 38, 88));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 6, 42, 88));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 6, 42, 88));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_r_50px_4.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 6, -1, 88));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 6, -1, 88));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 6, -1, 88));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_l_50px.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 6, -1, 88));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 6, -1, 88));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_50px.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, -4, 60, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 1210, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNumMAT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelNumMAT.setText("Num matériel");
        jPanel4.add(jLabelNumMAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 111, 60));

        jLabelNomMT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelNomMT.setText("Nom matériel");
        jPanel4.add(jLabelNomMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 20, 117, 47));

        jLabelTYMT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelTYMT.setText("Type matériel");
        jPanel4.add(jLabelTYMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 18, 136, 50));

        jLabelCarcMT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelCarcMT.setText("Caractéristique matériel");
        jPanel4.add(jLabelCarcMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 182, 49));

        TFNumMateriel.setBackground(new java.awt.Color(242, 242, 242));
        TFNumMateriel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNumMaterielKeyPressed(evt);
            }
        });
        jPanel4.add(TFNumMateriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 210, 50));

        TFNomMateriel.setBackground(new java.awt.Color(242, 242, 242));
        TFNomMateriel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNomMaterielKeyPressed(evt);
            }
        });
        jPanel4.add(TFNomMateriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 270, 50));

        TFCaracteristiquemateriel.setBackground(new java.awt.Color(242, 242, 242));
        TFCaracteristiquemateriel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFCaracteristiquematerielKeyPressed(evt);
            }
        });
        jPanel4.add(TFCaracteristiquemateriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 420, 50));

        TFTypeMateriel.setBackground(new java.awt.Color(242, 242, 242));
        TFTypeMateriel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTypeMaterielKeyPressed(evt);
            }
        });
        jPanel4.add(TFTypeMateriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 250, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 1200, 140));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(122, 72, 221));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 1190, 200));

        TFrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFrechActionPerformed(evt);
            }
        });
        jPanel1.add(TFrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 480, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_50px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 100, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setText("recherche par catégoie:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 60));

        CBrech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumMatériel", "NomMatériel", "TypeMatériel", "CaractéristiqueMtériel" }));
        jPanel1.add(CBrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void btnAjoutreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMouseClicked
        // TODO add your handling code here:
        ChekID(); 
        String NumM=TFNumMateriel.getText();
        String NomM=TFNomMateriel.getText();
        String T=TFTypeMateriel.getText();
        String C=TFCaracteristiquemateriel.getText();
        try {
        String sql="INSERT INTO `matérial`(`Nummatérial`, `Nom`, `Type`, `Caractéristique`) VALUES (?,?,?,?)";
        
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, NumM);
            prepared.setString(2, NomM);
            prepared.setString(3, T);
            prepared.setString(4, C);
            
            prepared.execute();
            refresh();
            
          
          System.out.println("ajouter avec succès");
          }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnAjoutreMouseClicked

    private void btnAjoutreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMousePressed
        // TODO add your handling code here:
        setcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnAjoutreMousePressed

    private void btnModiferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMousePressed
        // TODO add your handling code here:
        setcolor(btnModifer);
        resetcolor(btnAjoutre);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnModiferMousePressed

    private void btnSupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMousePressed
        // TODO add your handling code here:
         setcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnSupprimerMousePressed

    private void btnImprimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMousePressed
        // TODO add your handling code here:
        setcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnImprimeMousePressed

    private void btnValideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValideMousePressed
        // TODO add your handling code here:
        setcolor(btnValide);
        resetcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
    }//GEN-LAST:event_btnValideMousePressed

    private void btnValideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValideMouseClicked
        // TODO add your handling code here:
        TFNumMateriel.setText("");
        TFNomMateriel.setText("");
        TFTypeMateriel.setText("");
        TFCaracteristiquemateriel.setText("");
    }//GEN-LAST:event_btnValideMouseClicked

    private void TFrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFrechActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(TFrech.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else 
            
            if(CBrech.getSelectedItem().equals("NumMatériel")){
               try{
                    PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Nummatérial`, `Nom`, `Type`, `Carctéristique` FROM `matérial` WHERE `Nummatérial`="+TFrech.getText()+"");
                    ResultSet rs=pr.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(SQLException ex)
                        {
                        Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                        }
                     }else 
                            if(CBrech.getSelectedItem().equals("NomMatériel")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Nummatérial`, `Nom`, `Type`, `Carctéristique` FROM `matérial` WHERE `Nom`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("TypeMatériel")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Nummatérial`, `Nom`, `Type`, `Carctéristique` FROM `matérial` WHERE `Type`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("CaractéristiqueMtériel")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Nummatérial`, `Nom`, `Type`, `Carctéristique` FROM `matérial` WHERE `Carctéristique`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }
         



    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModiferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMouseClicked
        // TODO add your handling code here:
        String NumM=TFNumMateriel.getText();
        String NomM=TFNomMateriel.getText();
        String T=TFTypeMateriel.getText();
        String C=TFCaracteristiquemateriel.getText();
         if (NomM.equals("")||NomM.equals("")||C.equals(""))
        {
         JOptionPane.showMessageDialog(null,"champ vid","Error",JOptionPane.ERROR_MESSAGE);
        }
         String sql="UPDATE `matérial` SET `Nom`=?,`Type`=?,`Caractéristique`=?  WHERE  `Nummatérial`="+TFNumMateriel.getText()+"";
        
        try{
        prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, NomM);
            prepared.setString(2, T);
            prepared.setString(3, C);
            prepared.execute();
            refresh();
        }catch(SQLException e){
          System.out.println(e);
                  }
    }//GEN-LAST:event_btnModiferMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
        String m=TFNumMateriel.getText();
        try{
        String sql="DELETE FROM `matérial` WHERE `matérial`.`Nummatérial`= "+TFNumMateriel.getText()+"";
       int cho  = JOptionPane.showConfirmDialog(null,"Êtes-vous sûr de vouloir supprimer");
       if(  cho == JOptionPane.YES_OPTION) {
           prepared=(PreparedStatement) Login.cnx.prepareStatement(sql);
           prepared.execute();
           System.out.println("Supprimer avec succès");
       } else {
       }
        refresh();
        
        }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          int rowIndex=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        TFNumMateriel.setText(model.getValueAt(rowIndex, 0).toString());
        TFNomMateriel.setText(model.getValueAt(rowIndex, 1).toString());
        TFTypeMateriel.setText(model.getValueAt(rowIndex, 2).toString());
        TFCaracteristiquemateriel.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnImprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMouseClicked
        // TODO add your handling code here:
        String titer="liste des materiels";
           impression.imprimerJtable(jTable1, titer);
    }//GEN-LAST:event_btnImprimeMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        Pagechoix CP = new Pagechoix();
                    CP.show();
                    dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void TFNumMaterielKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNumMaterielKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        { TFNumMateriel.setEditable(false);
         jLabelNumMAT.setForeground(Color.red);
        }else{
             TFNumMateriel.setEditable(true);
             jLabelNumMAT.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFNumMaterielKeyPressed

    private void TFNomMaterielKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNomMaterielKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {   TFNomMateriel.setEditable(true);
         jLabelNomMT.setForeground(Color.black);
        }else{
               TFNomMateriel.setEditable(false);
             jLabelNomMT.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFNomMaterielKeyPressed

    private void TFTypeMaterielKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTypeMaterielKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFTypeMateriel.setEditable(true);
         jLabelTYMT.setForeground(Color.black);
        }else{
              TFTypeMateriel.setEditable(false);
             jLabelTYMT.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFTypeMaterielKeyPressed

    private void TFCaracteristiquematerielKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCaracteristiquematerielKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFCaracteristiquemateriel.setEditable(true);
         jLabelCarcMT.setForeground(Color.black);
        }else{
              TFCaracteristiquemateriel.setEditable(false);
             jLabelCarcMT.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFCaracteristiquematerielKeyPressed
void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(materiels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(materiels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(materiels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(materiels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new materiels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrech;
    private javax.swing.JTextField TFCaracteristiquemateriel;
    private javax.swing.JTextField TFNomMateriel;
    private javax.swing.JTextField TFNumMateriel;
    private javax.swing.JTextField TFTypeMateriel;
    private javax.swing.JTextField TFrech;
    private javax.swing.JPanel btnAjoutre;
    private javax.swing.JPanel btnImprime;
    private javax.swing.JPanel btnModifer;
    private javax.swing.JPanel btnSupprimer;
    private javax.swing.JPanel btnValide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCarcMT;
    private javax.swing.JLabel jLabelNomMT;
    private javax.swing.JLabel jLabelNumMAT;
    private javax.swing.JLabel jLabelTYMT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
