/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoirer;

/*import java.awt.Color;import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;*/
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
//import com.mysql.jdbc.Statement;
//import com.mysql.jdbc.Connection;
//import javax.swing.JOptionPane;
//import org.jdesktop.swingx.autocomplete.*;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.*;

/**
 *
 * @author PCexpress
 */
public class members extends javax.swing.JFrame {
    public static Connection cnx =DBConnexion.ConnectBD();
    PreparedStatement prepared=null;
    ResultSet resultat=null;
    int test=0;
    int t=0;
    
    /**
     * Creates new form members
     */
    public members() {
       initComponents();
       setLocationRelativeTo(null);
       ChekID();
       ChekDirecteur();
       refresh();
       
    }
    
            
    public void refresh(){
    Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT * FROM `membre` WHERE 1");
    ResultSet rs=pr.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex)
    {
    Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    public void ChekID(){
        Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT `Matricule` FROM `membre` WHERE 1");
    ResultSet rs=pr.executeQuery();
    while(rs.next()){
        String ID=rs.getString("Matricule");
        String id=TFMatricule.getText();
        if(ID.equals(id)){
            JOptionPane.showMessageDialog(null,"ce membre est dans les données");
            test=test+1;
        }else{
            
        }
    }
    }catch(SQLException e){
        e.printStackTrace();
    
    }
    }

    public void ChekDirecteur() {
    Connection co = DBConnexion.ConnectBD();
    try {
        PreparedStatement pr = co.prepareStatement("SELECT `Directeur` FROM `membre` WHERE `Directeur` = 1");
        ResultSet rs = pr.executeQuery();
        while (rs.next()) {
            if (Oui.isSelected()) {
                JOptionPane.showMessageDialog(null, "Directeur existe déjà dans les données. Impossible de l'ajouter");
                t = t + 1;
                return; // Exit the method if Directeur already exists
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}  
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAjoutre = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnvalide = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnModifer1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelMatricule = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        DateN = new com.toedter.calendar.JDateChooser();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        CBSpesialite = new javax.swing.JComboBox<>();
        CBGrade = new javax.swing.JComboBox<>();
        CBDiplome = new javax.swing.JComboBox<>();
        TFMatricule = new javax.swing.JTextField();
        TFNom = new javax.swing.JTextField();
        TFPrenom = new javax.swing.JTextField();
        TFtype = new javax.swing.JTextField();
        TFNequipe = new javax.swing.JTextField();
        TFtel = new javax.swing.JTextField();
        TFemail = new javax.swing.JTextField();
        TFrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CBrech = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Oui = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 50, 89));

        btnAjoutre.setBackground(new java.awt.Color(64, 43, 100));
        btnAjoutre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjoutreMousePressed(evt);
            }
        });

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnAjoutreLayout = new javax.swing.GroupLayout(btnAjoutre);
        btnAjoutre.setLayout(btnAjoutreLayout);
        btnAjoutreLayout.setHorizontalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnAjoutreLayout.setVerticalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        btnvalide.setBackground(new java.awt.Color(64, 43, 100));
        btnvalide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvalide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvalideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnvalideMousePressed(evt);
            }
        });

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_view_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnvalideLayout = new javax.swing.GroupLayout(btnvalide);
        btnvalide.setLayout(btnvalideLayout);
        btnvalideLayout.setHorizontalGroup(
            btnvalideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnvalideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnvalideLayout.setVerticalGroup(
            btnvalideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        btnSupprimer.setBackground(new java.awt.Color(64, 43, 100));
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupprimerMousePressed(evt);
            }
        });

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupprimerLayout = new javax.swing.GroupLayout(btnSupprimer);
        btnSupprimer.setLayout(btnSupprimerLayout);
        btnSupprimerLayout.setHorizontalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSupprimerLayout.setVerticalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        btnImprime.setBackground(new java.awt.Color(64, 43, 100));
        btnImprime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimeMousePressed(evt);
            }
        });

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_print_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnImprimeLayout = new javax.swing.GroupLayout(btnImprime);
        btnImprime.setLayout(btnImprimeLayout);
        btnImprimeLayout.setHorizontalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnImprimeLayout.setVerticalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        btnModifer1.setBackground(new java.awt.Color(64, 43, 100));
        btnModifer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifer1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModifer1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModifer1MousePressed(evt);
            }
        });

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnModifer1Layout = new javax.swing.GroupLayout(btnModifer1);
        btnModifer1.setLayout(btnModifer1Layout);
        btnModifer1Layout.setHorizontalGroup(
            btnModifer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModifer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnModifer1Layout.setVerticalGroup(
            btnModifer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reply_all_arrow_55px.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjoutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvalide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel22)
                .addGap(55, 55, 55)
                .addComponent(btnAjoutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnvalide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 140, 600));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_g_50px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 44, 88));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 6, 44, 88));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 6, 40, 88));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 6, 42, 88));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 6, 35, 88));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 6, -1, 88));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 6, -1, 88));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_d_50px.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 6, 42, 88));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 6, 44, 88));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 6, 46, 88));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_m_50px.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 6, 42, 88));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 6, 41, 88));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_m_50px.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 6, 41, 88));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_b_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 6, 42, 88));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_r_50px_4.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 6, 40, 88));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 6, 42, 88));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 6, 40, 88));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_50px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 58, 53));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 0, 1070, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMatricule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMatricule.setText("Matricule");
        jPanel4.add(jLabelMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 12, 70, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("sexe");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 66, 31));

        jLabelNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNom.setText("Nom");
        jPanel4.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 61, 66, 40));

        jLabelPrenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrenom.setText("Prénom");
        jPanel4.add(jLabelPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 66, 37));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Domaine");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 31));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Diplome");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 90, 31));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Grade");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, 31));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText(" Rôle");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, 31));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("DateNissance");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 31));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Num équipe");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 31));

        jLabelTel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTel.setText("Télephone");
        jPanel4.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 100, 31));

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmail.setText("Email");
        jPanel4.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 90, 31));
        jPanel4.add(DateN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 200, 40));

        buttonGroup1.add(Male);
        Male.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        jPanel4.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonGroup1.add(Female);
        Female.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Female.setText("Female");
        jPanel4.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        CBSpesialite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CBSpesialite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatique", "Ingenierie", "Mathematiques" }));
        jPanel4.add(CBSpesialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 112, 200, 40));

        CBGrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CBGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pr.", "Doc.", "MCA", "MCB", "MAA", "MAA, Doc.", "MAB", "MAB, Doc.", "DR", "MRA", "MRB", "CR", "AR, Doc.", "AR", "Per. de soutien" }));
        jPanel4.add(CBGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 200, 40));

        CBDiplome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CBDiplome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doc. d'Etat", "Doctorat", "Habilitation", "DESM", "Magister", "DEMS", "Master", "Licence", " " }));
        jPanel4.add(CBDiplome, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 180, 40));

        TFMatricule.setBackground(new java.awt.Color(242, 242, 242));
        TFMatricule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMatriculeKeyPressed(evt);
            }
        });
        jPanel4.add(TFMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 40));

        TFNom.setBackground(new java.awt.Color(242, 242, 242));
        TFNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNomKeyPressed(evt);
            }
        });
        jPanel4.add(TFNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 40));

        TFPrenom.setBackground(new java.awt.Color(242, 242, 242));
        TFPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFPrenomKeyPressed(evt);
            }
        });
        jPanel4.add(TFPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 40));

        TFtype.setBackground(new java.awt.Color(242, 242, 242));
        TFtype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtypeKeyPressed(evt);
            }
        });
        jPanel4.add(TFtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, 40));

        TFNequipe.setBackground(new java.awt.Color(242, 242, 242));
        TFNequipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNequipeKeyPressed(evt);
            }
        });
        jPanel4.add(TFNequipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 12, 180, 40));

        TFtel.setBackground(new java.awt.Color(242, 242, 242));
        TFtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFtelKeyTyped(evt);
            }
        });
        jPanel4.add(TFtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 60, 180, 40));

        TFemail.setBackground(new java.awt.Color(242, 242, 242));
        TFemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFemailKeyTyped(evt);
            }
        });
        jPanel4.add(TFemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 180, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 1060, 210));

        TFrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFrechActionPerformed(evt);
            }
        });
        jPanel1.add(TFrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 380, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_50px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 110, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 1060, 210));

        CBrech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricule", "Nom", "Prenom", "sexe", "Grade", "Spesialite", "type", "Numequipe", "Tel", "Email", "Directeur" }));
        jPanel1.add(CBrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setText("recherche par catégoie:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 110, 180, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89))));

        buttonGroup2.add(Oui);
        Oui.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Oui.setText("Oui");
        Oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OuiActionPerformed(evt);
            }
        });

        buttonGroup2.add(No);
        No.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        No.setText("No");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Directeur :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(No)
                .addGap(9, 9, 9))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oui)
                    .addComponent(No))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 230, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnAjoutreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMousePressed
        // TODO add your handling code here:
        setcolor(btnAjoutre);
        resetcolor(btnvalide);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
    }//GEN-LAST:event_btnAjoutreMousePressed

    private void btnvalideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalideMousePressed
        // TODO add your handling code here:
        setcolor(btnvalide);
        resetcolor(btnAjoutre);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
    }//GEN-LAST:event_btnvalideMousePressed

    private void btnSupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMousePressed
        // TODO add your handling code here:
         setcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnvalide);
        resetcolor(btnImprime);
    }//GEN-LAST:event_btnSupprimerMousePressed

    private void btnImprimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMousePressed
        // TODO add your handling code here:
        setcolor(btnImprime);
        resetcolor(btnvalide);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
    }//GEN-LAST:event_btnImprimeMousePressed

    private void btnModifer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifer1MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnModifer1MousePressed

    private void btnvalideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalideMouseClicked
        // TODO add your handling code here:
        TFMatricule.setText("");
        TFNom.setText("");
        TFPrenom.setText("");
        buttonGroup1.clearSelection();
        CBGrade.setSelectedIndex(0);
        CBSpesialite.setSelectedIndex(0);
        TFtype.setText("");
        TFNequipe.setText("");
        TFtel.setText("");
        TFemail.setText("");
        CBDiplome.setSelectedIndex(0);
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btnvalideMouseClicked

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void btnAjoutreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMouseClicked
        // TODO add your handling code here:
        ChekID();
        ChekDirecteur();
        String m=TFMatricule.getText();
        String n=TFNom.getText();
        String p=TFPrenom.getText();
        String s = null;
        if(Male.isSelected())
            {
            s="Male";
            }if(Female.isSelected())
            {
            s="Female";
            }
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String DN=sdf.format(DateN.getDate());

        
        String gr=CBGrade.getSelectedItem().toString();
        String SP=CBSpesialite.getSelectedItem().toString();
        String TP=TFtype.getText();
        String IDEq=TFNequipe.getText();
        String tel=TFtel.getText();
        String Em=TFemail.getText();
        String Dp=CBDiplome.getSelectedItem().toString();
        String Dr = null;
        if(Oui.isSelected())
            {
            Dr="1";
            }if(No.isSelected())
            {
            Dr="0";
            }
            

        try {
        String sql="INSERT INTO `membre`(`Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome`, `Directeur`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        String sQl="INSERT INTO `utilisateurs`(`id`, `NomUtilisateur`, `Password`, `Type`, `Directeur`) VALUES (?,?,?,?,?)";
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, m);
            prepared.setString(2, n);
            prepared.setString(3, p);
            prepared.setString(4, s); 
            if (DateN == null){
              DN="";
             }
             Date dateNaissance = DateN.getDate();
             java.util.Calendar referenceDate = java.util.Calendar.getInstance();
             referenceDate.set(1994, java.util.Calendar.JANUARY, 1);
             java.util.Calendar selectedDate = java.util.Calendar.getInstance();
             selectedDate.setTime(dateNaissance);
            if (selectedDate.before(referenceDate)) {
            prepared.setDate(5, new java.sql.Date(dateNaissance.getTime()));
            //prepared.setString(5, DN);
            } else {
            // Faites quelque chose si la date sélectionnée est inférieure ou égale à "1990-01-01"
            // Par exemple, vous pouvez afficher un message d'erreur ou effectuer une autre action
            // Vous pouvez également réinitialiser la valeur du champ de date
            JOptionPane.showMessageDialog(null, "Donnez votre date de naissance", "Erreur de date", JOptionPane.ERROR_MESSAGE);
            return; // Arrête l'exécution du code pour éviter d'insérer des données incorrectes
            }
            prepared.setString(5, DN);
            prepared.setString(6, gr);
            prepared.setString(7, SP);
            prepared.setString(8, TP);
            prepared.setString(9, IDEq);
            prepared.setString(10, tel);
            prepared.setString(11, Em);
            prepared.setString(12, Dp);
            if(t>0){
                Dr="0";}
             prepared.setString(13, Dr);
            
            prepared.execute();
             refresh();
            
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sQl);
            prepared.setString(1, m);
            prepared.setString(2, n);
            prepared.setString(3, "12345678");
            prepared.setString(4, TP);
            if(t>0){
              Dr="0";}
             prepared.setString(5, Dr);
            prepared.execute();
             
             
          System.out.println("ajouter avec succès");
          }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnAjoutreMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        TFMatricule.setText(model.getValueAt(rowIndex, 0).toString());
        TFNom.setText(model.getValueAt(rowIndex, 1).toString());
        TFPrenom.setText(model.getValueAt(rowIndex, 2).toString());
        String s=model.getValueAt(rowIndex, 3).toString();
       if(s.equals("Male"))
       {
           Male.setSelected(true);
       }else
       {
       Female.setSelected(true);
       }
        try{
            DateN.setDate((Date) (model.getValueAt(rowIndex, 4)));
        } catch(Exception e)
        {
      JOptionPane.showMessageDialog(null,e);
       }
        String GR=model.getValueAt(rowIndex, 5).toString();
        switch (GR){
            case "Pr." : CBGrade.setSelectedIndex(0);
            break;
            case "Doc." : CBGrade.setSelectedIndex(1);
             break;
            case "MCA" : CBGrade.setSelectedIndex(2);
             break;
            case "MCB" :CBGrade.setSelectedIndex(3);
         break;
         case "MAA" : CBGrade.setSelectedIndex(4);
            break;
            case "MAA, Doc." : CBGrade.setSelectedIndex(5);
            break;
         case "MAB" : CBGrade.setSelectedIndex(6);
            break;
             case "MAB, Doc." : CBGrade.setSelectedIndex(7);
            break;
          case "DR" : CBGrade.setSelectedIndex(8);
            break;
            case "MRA" : CBGrade.setSelectedIndex(9);
            break;
            case "MRB" : CBGrade.setSelectedIndex(10);
            break;
            case "CR" : CBGrade.setSelectedIndex(11);
            break;
            case "AR, Doc." : CBGrade.setSelectedIndex(12);
            break;
            case "AR" : CBGrade.setSelectedIndex(13);
            break;
            case "Per. de soutien" : CBGrade.setSelectedIndex(14);
            break;
}
        String SP=model.getValueAt(rowIndex, 6).toString();
        switch (SP){
            case "Informatique" : CBSpesialite.setSelectedIndex(0);
            break;
            case "Ingenierie" : CBSpesialite.setSelectedIndex(1);
            break;
            case "Mathematiques" : CBSpesialite.setSelectedIndex(2);
            break;
            }
        TFtype.setText(model.getValueAt(rowIndex, 7).toString());
        
       TFNequipe.setText(model.getValueAt(rowIndex, 8).toString());
       /*String p=model.getValueAt(rowIndex, 9).toString();
        switch (p){
            case "Afrique du Sud"   -> jC.setSelectedIndex(0);
            case "Allemange"          -> jC.setSelectedIndex(1);
            case "Arabie Saoudite"           -> jC.setSelectedIndex(2);
            case "Bahrein"           -> jC.setSelectedIndex(3);
            case "Belgique"           -> jC.setSelectedIndex(4);
            case "Brésil"           -> jC.setSelectedIndex(5);
            case "Canada"           -> jC.setSelectedIndex(6);
            case "Chili"           -> jC.setSelectedIndex(7);
            case "Chine"           -> jC.setSelectedIndex(8);
            case "Egypte"           -> jC.setSelectedIndex(9);
            case "Emirate Arabs Unis"           -> jC.setSelectedIndex(10);
            case "Espagne"           -> jC.setSelectedIndex(11);
            case "Etats-Unis d'Amérique"           -> jC.setSelectedIndex(12);
            case "Finlande"           -> jC.setSelectedIndex(13);
            case "France"           -> jC.setSelectedIndex(14);
            case "Hollande"           -> jC.setSelectedIndex(15);
            case "Hongrie"           -> jC.setSelectedIndex(16);
            case "Ile Maurice"           -> jC.setSelectedIndex(17);
            case "Italie"           -> jC.setSelectedIndex(18);
            case "Jordanie"           -> jC.setSelectedIndex(19);
            case "Koweit"           -> jC.setSelectedIndex(20);
            case "Liban"           -> jC.setSelectedIndex(21);
            case "Malaisie"           -> jC.setSelectedIndex(22);
            case "Malaysia"           -> jC.setSelectedIndex(23);
            case "Maroc"           -> jC.setSelectedIndex(24);
            case "Oman"           -> jC.setSelectedIndex(25);
            case "Portugal"           -> jC.setSelectedIndex(26);
            case "Qatar"           -> jC.setSelectedIndex(27);
            case "Royaume-Uni"           -> jC.setSelectedIndex(28);
            case "Russie"           -> jC.setSelectedIndex(29);
            case "Stockholm"           -> jC.setSelectedIndex(30);
            case "Suisse"           -> jC.setSelectedIndex(31);
            case "Tchéque"           -> jC.setSelectedIndex(32);
            case "Tunisie"           -> jC.setSelectedIndex(33);
            case "Turquie"           -> jC.setSelectedIndex(34);
        }*/
       TFtel.setText(model.getValueAt(rowIndex, 9).toString());
       TFemail.setText(model.getValueAt(rowIndex, 10).toString());
      /* String d=model.getValueAt(rowIndex, 11).toString();
        switch (d){
            case "électronique"   -> dom.setSelectedIndex(0);
            case "électrotechnique"          -> dom.setSelectedIndex(1);
            case "Génie Des Procédés"           -> dom.setSelectedIndex(2);
            case "Génie De L'irrigartion"           -> dom.setSelectedIndex(3);
            case "Mécanique"           -> dom.setSelectedIndex(4);
            case "Génie Civil"           -> dom.setSelectedIndex(5);
            case "Trvaux Publics"           -> dom.setSelectedIndex(6);
            case "Architecture"           -> dom.setSelectedIndex(7);
            case "Mathématiques"           -> dom.setSelectedIndex(8);
            case "informatique"           -> dom.setSelectedIndex(9);
            case "Physique"           -> dom.setSelectedIndex(10);
            case "Chimie"           -> dom.setSelectedIndex(11);
            case "Sciences agronomiques"           -> dom.setSelectedIndex(12);
            case "Biologie"           -> dom.setSelectedIndex(13);
            case "Géologie"           -> dom.setSelectedIndex(14);
            case "Vétérinaire"           -> dom.setSelectedIndex(15);
            case "Sciences économiques"           -> dom.setSelectedIndex(16);
            case "Sciences Commerciales"           -> dom.setSelectedIndex(17);
            case "Sciences De Gestion"           -> dom.setSelectedIndex(18);
            case "droits"           -> dom.setSelectedIndex(19);
            case "Sciences Politiques"           -> dom.setSelectedIndex(20);
            case "Littératue Arabe"           -> dom.setSelectedIndex(21);
            case "Francais"           -> dom.setSelectedIndex(22);
            case "Anglais"           -> dom.setSelectedIndex(23);
            case "Espagnol"           -> dom.setSelectedIndex(24);
            case "Sciences Sociales"           -> dom.setSelectedIndex(25);
            case "Sciences Humaines"           -> dom.setSelectedIndex(26);
            case "Sciences Islamiques"           -> dom.setSelectedIndex(27);
            case "Sciences médicals"           -> dom.setSelectedIndex(28);
            case "Téchnique physiqes"           -> dom.setSelectedIndex(29);
            case "Téchnique Sportives"           -> dom.setSelectedIndex(30);
         }*/
       
       String Dp=model.getValueAt(rowIndex, 11).toString();
        switch (Dp){
            case "Doc. d'Etat" : CBDiplome.setSelectedIndex(0);
            break;
            case "Doctorat" : CBDiplome.setSelectedIndex(1);
             break;
            case "Habilitation" : CBDiplome.setSelectedIndex(2);
             break;
            case "DESM" :CBDiplome.setSelectedIndex(3);
         break;
         case "Magister" : CBDiplome.setSelectedIndex(4);
            break;
            case "DEMS" : CBDiplome.setSelectedIndex(5);
            break;
         case "Master" : CBDiplome.setSelectedIndex(6);
            break;
            case "Licence" : CBDiplome.setSelectedIndex(7);
            break;
        }
        String Dr=model.getValueAt(rowIndex, 12).toString();
         if(Dr.equals("true"))
       {
           Oui.setSelected(true);
         }else
        {
            No.setSelected(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
         String m=TFMatricule.getText();
        try{
        String sql="DELETE FROM `membre` WHERE `membre`.`Matricule`= "+TFMatricule.getText()+"";
        String sQl="DELETE FROM `utilisateurs` WHERE `utilisateurs`.`id`="+TFMatricule.getText()+"";
        
        prepared=(PreparedStatement) Login.cnx.prepareStatement(sQl);
       int cho  = JOptionPane.showConfirmDialog(null,"Êtes-vous sûr de vouloir supprimer");
       if(  cho == JOptionPane.YES_OPTION) {
           prepared.execute();
           prepared=(PreparedStatement) Login.cnx.prepareStatement(sql);
           prepared.execute();
           System.out.println("Supprimer avec succès");
       } else {
       }
        refresh();
        
        }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void btnModifer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifer1MouseClicked
        // TODO add your handling code here:
        ChekDirecteur();
        String m=TFMatricule.getText();
        String n=TFNom.getText();
        String p=TFPrenom.getText();
        String s = null;
        if(Male.isSelected())
            {
            s="Male";
            }if(Female.isSelected())
            {
            s="Female";
            }
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String DN=sdf.format(DateN.getDate());
        String gr=CBGrade.getSelectedItem().toString();
        String SP=CBSpesialite.getSelectedItem().toString();
        String TP=TFtype.getText();
        String IDEq=TFNequipe.getText();
        String tel=TFtel.getText();
        String Em=TFemail.getText();
        String Dp=CBDiplome.getSelectedItem().toString();
        String Dr = null;
        if(Oui.isSelected())
            {
            Dr="1";
            }if(No.isSelected())
            {
            Dr="0";
            }
         if (n.equals("")||p.equals("")||s.equals("")||DN.equals("")||gr.equals("")||SP.equals("")||TP.equals("")||IDEq.equals("")||tel.equals("")||Em.equals("")||Dp.equals("")||Dr.equals(""))
        {
         JOptionPane.showMessageDialog(null,"champ vid","Error",JOptionPane.ERROR_MESSAGE);
        }
         String sql="UPDATE `membre` SET `Nom`=?,`Prenom`=?,`sexe`=?,`DN`=?,`Grade`=?,`Spesialite`=?,`type`=?,`Numequipe`=?,`Tel`=?,`Email`=?,`Diplome`=?, `Directeur`=? WHERE  `Matricule`="+TFMatricule.getText()+"";
        String sQl="UPDATE `utilisateurs` SET `NomUtilisateur`=?,`Type`=? , `Directeur`=? WHERE  `id`="+TFMatricule.getText()+"";
        try{
        prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
          
            prepared.setString(1, n);
            prepared.setString(2, p);
            prepared.setString(3, s);
             Date dateNaissance = DateN.getDate();
             java.util.Calendar referenceDate = java.util.Calendar.getInstance();
             referenceDate.set(1994, java.util.Calendar.JANUARY, 1);
             java.util.Calendar selectedDate = java.util.Calendar.getInstance();
             selectedDate.setTime(dateNaissance);
            if (selectedDate.before(referenceDate)) {
            prepared.setDate(4, new java.sql.Date(dateNaissance.getTime()));
            } else {
            // Faites quelque chose si la date sélectionnée est inférieure ou égale à "1990-01-01"
            // Par exemple, vous pouvez afficher un message d'erreur ou effectuer une autre action
            // Vous pouvez également réinitialiser la valeur du champ de date
            JOptionPane.showMessageDialog(null, "Donnez votre date de naissance", "Erreur de date", JOptionPane.ERROR_MESSAGE);
            return; // Arrête l'exécution du code pour éviter d'insérer des données incorrectes
            }
            //prepared.setString(4, DN);
            prepared.setString(5, gr);
            prepared.setString(6, SP);
            prepared.setString(7, TP);
            prepared.setString(8, IDEq);
            prepared.setString(9, tel);
            prepared.setString(10, Em);
            prepared.setString(11, Dp);
            if(t>0){
                Dr="0";
            }
            prepared.setString(12, Dr);
            prepared.execute();
             refresh();
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sQl);
            
            prepared.setString(1, n);
            prepared.setString(2, TP);
            if(t>0){
                Dr="0";
            }
            prepared.setString(3, Dr);
            prepared.execute();
            System.out.println("Modifié avec succès");
        
        }catch(SQLException e){
          System.out.println(e);
        }
        
    }//GEN-LAST:event_btnModifer1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(TFrech.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else 
            
            if(CBrech.getSelectedItem().equals("Matricule")){
               try{
                    PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Matricule`="+TFrech.getText()+"");
                    ResultSet rs=pr.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(SQLException ex)
                        {
                        Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                        }
                     }else 
                            if(CBrech.getSelectedItem().equals("Nom")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Nom`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                                    if(CBrech.getSelectedItem().equals("Prenom")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Prenom`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("sexe")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `sexe`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Grade")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Grade`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Spesialite")){
                               try{
                                
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Spesialite`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("type")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `type`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Numequipe")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Numequipe`="+TFrech.getText()+"");
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Tel")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Tel`="+TFrech.getText()+"");
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Email")){
                               try{
                                
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Email`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                
                            }
                                if(CBrech.getSelectedItem().equals("Directeur")){
                               try{
                                
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Matricule`, `Nom`, `Prenom`, `sexe`, `DN`, `Grade`, `Spesialite`, `type`, `Numequipe`, `Tel`, `Email`, `Diplome` FROM `membre` WHERE `Directeur`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFrechActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void OuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OuiActionPerformed

    private void btnImprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMouseClicked
        // TODO add your handling code here:
        String titer="liste des members";
           impression.imprimerJtable(jTable1, titer);
    }//GEN-LAST:event_btnImprimeMouseClicked

    private void btnModifer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifer1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifer1MouseEntered

    private void TFMatriculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMatriculeKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {TFMatricule.setEditable(false);
         jLabelMatricule.setForeground(Color.red);
        }else{
            TFMatricule.setEditable(true);
             jLabelMatricule.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFMatriculeKeyPressed

    private void TFNequipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNequipeKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {TFNequipe.setEditable(false);
         jLabel28.setForeground(Color.red);
        }else{
            TFNequipe.setEditable(true);
             jLabel28.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFNequipeKeyPressed

    private void TFNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNomKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFNom.setEditable(true);
         jLabelNom.setForeground(Color.black);
        }else{
              TFNom.setEditable(false);
             jLabelNom.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFNomKeyPressed

    private void TFPrenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPrenomKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFPrenom.setEditable(true);
         jLabelPrenom.setForeground(Color.black);
        }else{
              TFPrenom.setEditable(false);
             jLabelPrenom.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFPrenomKeyPressed

    private void TFtypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtypeKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isAlphabetic(c) || Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c) || Character.isBmpCodePoint(c)
                )
        {  TFtype.setEditable(true);
         jLabel26.setForeground(Color.black);
        }else{
              TFtype.setEditable(false);
             jLabel26.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFtypeKeyPressed

    private void TFtelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtelKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TFtelKeyPressed

    private void TFtelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtelKeyTyped
        // TODO add your handling code here:
        String input = String.valueOf(evt.getKeyChar());
            String phoneNumber = TFtel.getText() + input;


        char x=evt.getKeyChar();
      if(Character.isLetter(x) || Character.isWhitespace(x))
      {
          TFtel.setEditable(false);
          jLabelTel.setForeground(Color.red);
      }else{
         
        if (phoneNumber.length() > 10 && !phoneNumber.matches("\\d{10}")) {
        evt.consume();
        }
      TFtel.setEditable(true);
          jLabelTel.setForeground(Color.black);
      }
    }//GEN-LAST:event_TFtelKeyTyped

    private void TFemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFemailKeyTyped
        // TODO add your handling code here:
     /*   String text = TFemail.getText();

    // Récupérer le caractère saisi
    char input = evt.getKeyChar();

    // Concaténer le caractère saisi avec le texte existant
    String email = text + input;

    // Vérifier si la taille de l'email dépasse la limite autorisée (ici, nous fixons une limite de 50 caractères)
    if (email.length() > 50) {
        evt.consume();  // Bloquer la saisie du caractère
        return;
    }

    // Vérifier si le caractère saisi est un espace, une lettre, un chiffre, un point ou un tiret
    if (!(Character.isLetterOrDigit(input) || input == '.' || input == '-' || Character.isWhitespace(input))) {
        evt.consume();  // Bloquer la saisie du caractère
        return;
    }

    // Vérifier le format de l'email à l'aide d'une expression régulière
    String emailRegex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
    if (!email.matches(emailRegex)) {
        jLabelEmail.setForeground(Color.red);
    } else {
        jLabelEmail.setForeground(Color.black);
    }*/
    }//GEN-LAST:event_TFemailKeyTyped

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        WindowDirecteur CP = new WindowDirecteur();
                    CP.show();
                    dispose();
        
    }//GEN-LAST:event_jLabel22MouseClicked

     void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new members().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDiplome;
    private javax.swing.JComboBox<String> CBGrade;
    private javax.swing.JComboBox<String> CBSpesialite;
    private javax.swing.JComboBox<String> CBrech;
    private com.toedter.calendar.JDateChooser DateN;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton Oui;
    private javax.swing.JTextField TFMatricule;
    private javax.swing.JTextField TFNequipe;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPrenom;
    private javax.swing.JTextField TFemail;
    private javax.swing.JTextField TFrech;
    private javax.swing.JTextField TFtel;
    private javax.swing.JTextField TFtype;
    private javax.swing.JPanel btnAjoutre;
    private javax.swing.JPanel btnImprime;
    private javax.swing.JPanel btnModifer1;
    private javax.swing.JPanel btnSupprimer;
    private javax.swing.JPanel btnvalide;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMatricule;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
