/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoirer;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static laboratoirer.members.cnx;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PCexpress
 */
public class projet extends javax.swing.JFrame {
     public static Connection cnx =DBConnexion.ConnectBD();
    PreparedStatement prepared=null;
    ResultSet resultat=null;
    int test=0;
   private JFrame previousPage;
    
    /**
     * Creates new form projet
     */
    
    public projet() {
        initComponents();
        setLocationRelativeTo(null);
        ChekID();
        refresh();   
    }
    

     public void refresh(){
    Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT * FROM `projet` WHERE 1");
    ResultSet rs=pr.executeQuery();
    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex)
    {
    Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    public void ChekID(){
        Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT `NumProjet` FROM `projet` WHERE 1");
    ResultSet rs=pr.executeQuery();
    while(rs.next()){
        String ID=rs.getString("NumProjet");
        String id=TFIDprojet.getText();
        if(ID.equals(id)){
            JOptionPane.showMessageDialog(null,"ce projet est dans les données");
            test=test+1;
        }else{
            
        }
    }
    }catch(SQLException e){
        e.printStackTrace();
    
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAjoutre = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnModifer = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnValide = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelIDprojet = new javax.swing.JLabel();
        jLabelTitreP = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();
        bb = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        duré = new javax.swing.JButton();
        Dt_dep = new com.toedter.calendar.JDateChooser();
        Dt_ar = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        TFIDprojet = new javax.swing.JTextField();
        TFTitreP = new javax.swing.JTextField();
        duréaffiche = new javax.swing.JTextField();
        Domine = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TFrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        CBrech = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        btnAjoutre.setBackground(new java.awt.Color(64, 43, 100));
        btnAjoutre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjoutreMousePressed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnAjoutreLayout = new javax.swing.GroupLayout(btnAjoutre);
        btnAjoutre.setLayout(btnAjoutreLayout);
        btnAjoutreLayout.setHorizontalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAjoutreLayout.setVerticalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnModifer.setBackground(new java.awt.Color(64, 43, 100));
        btnModifer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifer.setPreferredSize(new java.awt.Dimension(133, 75));
        btnModifer.setRequestFocusEnabled(false);
        btnModifer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModiferMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModiferMousePressed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnModiferLayout = new javax.swing.GroupLayout(btnModifer);
        btnModifer.setLayout(btnModiferLayout);
        btnModiferLayout.setHorizontalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnModiferLayout.setVerticalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSupprimer.setBackground(new java.awt.Color(64, 43, 100));
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupprimerMousePressed(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupprimerLayout = new javax.swing.GroupLayout(btnSupprimer);
        btnSupprimer.setLayout(btnSupprimerLayout);
        btnSupprimerLayout.setHorizontalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSupprimerLayout.setVerticalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnImprime.setBackground(new java.awt.Color(64, 43, 100));
        btnImprime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprime.setPreferredSize(new java.awt.Dimension(133, 75));
        btnImprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimeMousePressed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_print_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnImprimeLayout = new javax.swing.GroupLayout(btnImprime);
        btnImprime.setLayout(btnImprimeLayout);
        btnImprimeLayout.setHorizontalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnImprimeLayout.setVerticalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnValide.setBackground(new java.awt.Color(64, 43, 100));
        btnValide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValideMousePressed(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_view_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnValideLayout = new javax.swing.GroupLayout(btnValide);
        btnValide.setLayout(btnValideLayout);
        btnValideLayout.setHorizontalGroup(
            btnValideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        btnValideLayout.setVerticalGroup(
            btnValideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnValideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reply_all_arrow_55px.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjoutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModifer, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnImprime, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(btnValide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnAjoutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_g_50px.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_d_50px.png"))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_p_50px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_r_50px_4.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_j_50px.png"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_50px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 0, 1110, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIDprojet.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelIDprojet.setText("Num projet");
        jPanel4.add(jLabelIDprojet, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 14, -1, 44));

        jLabelTitreP.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelTitreP.setText("Titre projet");
        jPanel4.add(jLabelTitreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, 81, 37));

        aa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        aa.setText("Date Dubét projet");
        jPanel4.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 26, -1, -1));

        bb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bb.setText("Date Fin Projet");
        jPanel4.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 107, 126, 26));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setText("Néquipe");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 110, 70, -1));

        duré.setBackground(new java.awt.Color(242, 242, 242));
        duré.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        duré.setText("DureéProjet");
        duré.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duréActionPerformed(evt);
            }
        });
        jPanel4.add(duré, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 24, -1, -1));
        jPanel4.add(Dt_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 170, 40));
        jPanel4.add(Dt_ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 102, 170, 40));

        jLabel20.setText("Jour");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 30, 40));

        TFIDprojet.setBackground(new java.awt.Color(242, 242, 242));
        TFIDprojet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFIDprojetKeyPressed(evt);
            }
        });
        jPanel4.add(TFIDprojet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, 40));

        TFTitreP.setBackground(new java.awt.Color(242, 242, 242));
        TFTitreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTitrePKeyPressed(evt);
            }
        });
        jPanel4.add(TFTitreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, 40));

        duréaffiche.setBackground(new java.awt.Color(242, 242, 242));
        duréaffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duréafficheActionPerformed(evt);
            }
        });
        jPanel4.add(duréaffiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 170, 40));

        Domine.setBackground(new java.awt.Color(242, 242, 242));
        Domine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DomineKeyPressed(evt);
            }
        });
        jPanel4.add(Domine, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 170, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 1110, 170));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(122, 72, 221));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 1100, 240));

        TFrech.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TFrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFrechActionPerformed(evt);
            }
        });
        jPanel1.add(TFrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 420, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_50px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 100, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setText("recherche par catégoie:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 170, 50));

        CBrech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumProjet", "TitreProjet", "DureéProjet", "Numequipe" }));
        CBrech.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBrechActionPerformed(evt);
            }
        });
        jPanel1.add(CBrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btnAjoutreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMousePressed
        // TODO add your handling code here:
         setcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnAjoutreMousePressed

    private void btnModiferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMousePressed
        // TODO add your handling code here:
         setcolor(btnModifer);
        resetcolor(btnAjoutre);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnModiferMousePressed

    private void btnSupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMousePressed
        // TODO add your handling code here:
        setcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnImprime);
        resetcolor(btnValide);
    }//GEN-LAST:event_btnSupprimerMousePressed

    private void btnImprimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMousePressed
        // TODO add your handling code here:
        setcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
         resetcolor(btnValide);
    }//GEN-LAST:event_btnImprimeMousePressed

    private void duréActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duréActionPerformed
        // TODO add your handling code here:
         try{
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        Date a=Dt_dep.getDate();
        Date b=Dt_ar.getDate();
        long d=Math.abs(a.getTime()-b.getTime());
        long diff=TimeUnit.DAYS.convert(d, TimeUnit.MILLISECONDS);
        duréaffiche.setText(String.valueOf(diff));
            
        }catch(Exception e){
        
        }
    
    }//GEN-LAST:event_duréActionPerformed

    private void btnValideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValideMousePressed
        // TODO add your handling code here:
        setcolor(btnValide);
        resetcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
    }//GEN-LAST:event_btnValideMousePressed

    private void btnValideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValideMouseClicked
        // TODO add your handling code here:
        TFIDprojet.setText("");
        TFTitreP.setText("");
        duréaffiche.setText("");
        Domine.setText("");
    }//GEN-LAST:event_btnValideMouseClicked

    private void btnAjoutreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMouseClicked
        // TODO add your handling code here:
         ChekID(); 
        String m=TFIDprojet.getText();
        String n=TFTitreP.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String Dd=sdf.format(Dt_dep.getDate());
        String Df=sdf.format(Dt_ar.getDate());
         String Dur=duréaffiche.getText();
        String Dom=Domine.getText();
        try {
        String sql="INSERT INTO `projet`(`NumProjet`, `Titre`, `DateDébut`, `Darefin`, `Dur`, `Numequipe`) VALUES (?,?,?,?,?,?)";
        
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, m);
            prepared.setString(2, n);
            prepared.setString(3, Dd);
            prepared.setString(4, Df);
            prepared.setString(5, Dur);
            prepared.setString(6,Dom );
            prepared.execute();
            refresh();
            
          
          System.out.println("ajouter avec succès");
          }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnAjoutreMouseClicked

    private void btnModiferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMouseClicked
        // TODO add your handling code here:
         String m=TFIDprojet.getText();
        String n=TFTitreP.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String Dd=sdf.format(Dt_dep.getDate());
        String Df=sdf.format(Dt_ar.getDate());
         String Dur=duréaffiche.getText();
        String Dom=Domine.getText();
         if (n.equals("")||Dd.equals("")||Df.equals("")||Dur.equals("")||Dom.equals(""))
        {
         JOptionPane.showMessageDialog(null,"champ vid","Error",JOptionPane.ERROR_MESSAGE);
        }
         String sql="UPDATE `projet` SET `Titre`=?,`DateDébut`=?,`Darefin`=?,`Dur`=? WHERE  `NumProjet`="+TFIDprojet.getText()+"";
        
        try{
        prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
          
           
            prepared.setString(1, n);
            prepared.setString(2, Dd);
            prepared.setString(3, Df);
           // prepared.setString(4, Dom);
            prepared.setString(4, Dur);
            prepared.execute();
            refresh();
        }catch(SQLException e){
          System.out.println(e);
        }      
    }//GEN-LAST:event_btnModiferMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
         String m=TFIDprojet.getText();
        try{
        String sql="DELETE FROM `projet` WHERE `projet`.`NumProjet`= "+TFIDprojet.getText()+"";
       int cho  = JOptionPane.showConfirmDialog(null,"Êtes-vous sûr de vouloir supprimer");
       if(  cho == JOptionPane.YES_OPTION) {
           prepared=(PreparedStatement) Login.cnx.prepareStatement(sql);
           prepared.execute();
           System.out.println("Supprimer avec succès");
       } else {
       }
        refresh();
        
        }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void CBrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBrechActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(TFrech.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else 
            
            if(CBrech.getSelectedItem().equals("NumProjet")){
               try{
                    PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `NumProjet`, `Titre`, `DateDébut`, `Darefin`, `Dur`, `Numequipe` FROM `projet` WHERE `NumProjet`="+TFrech.getText()+"");
                    ResultSet rs=pr.executeQuery();
                    jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(SQLException ex)
                        {
                        Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                        }
                     }else 
                            if(CBrech.getSelectedItem().equals("TitreProjet")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `projet` WHERE `Titre`=?");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                                    if(CBrech.getSelectedItem().equals("DureéProjet")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `projet` WHERE `Dur`="+TFrech.getText()+"");
                                ResultSet rs=pr.executeQuery();
                                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }else 
                            if(CBrech.getSelectedItem().equals("Numequipe")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `projet` WHERE `Numequipe`="+TFrech.getText()+"");
                                pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                
                            
                               
                                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         int rowIndex=jTable2.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        TFIDprojet.setText(model.getValueAt(rowIndex, 0).toString());
        TFTitreP.setText(model.getValueAt(rowIndex, 1).toString());
    
        try{
            Dt_dep.setDate((Date) (model.getValueAt(rowIndex, 2)));
        } catch(Exception e)
        {
      JOptionPane.showMessageDialog(null,e);
       }
        try{
            Dt_ar.setDate((Date) (model.getValueAt(rowIndex, 3)));
        } catch(Exception e)
        {
      JOptionPane.showMessageDialog(null,e);
       }
        
        duréaffiche.setText(model.getValueAt(rowIndex,4 ).toString());
        
       Domine.setText(model.getValueAt(rowIndex, 5).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void TFrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFrechActionPerformed

    private void btnImprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMouseClicked
        // TODO add your handling code here:
        String titer="liste des projet";
           impression.imprimerJtable(jTable2, titer);
    }//GEN-LAST:event_btnImprimeMouseClicked

    
    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         WindowDirecteur CP = new WindowDirecteur();
                    CP.show();
                    dispose();
                                              
   
                           


  
   



    }//GEN-LAST:event_jLabel21MouseClicked

   
    private void duréafficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duréafficheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duréafficheActionPerformed

    private void DomineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DomineKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        { Domine.setEditable(false);
         jLabel24.setForeground(Color.red);
        }else{
             Domine.setEditable(true);
             jLabel24.setForeground(Color.black);
        }
    }//GEN-LAST:event_DomineKeyPressed

    private void TFIDprojetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFIDprojetKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {  TFIDprojet.setEditable(false);
         jLabelIDprojet.setForeground(Color.red);
        }else{
              TFIDprojet.setEditable(true);
             jLabelIDprojet.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFIDprojetKeyPressed

    private void TFTitrePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTitrePKeyPressed
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)
                )
        {  TFTitreP.setEditable(true);
         jLabelTitreP.setForeground(Color.black);
        }else{
              TFTitreP.setEditable(false);
             jLabelTitreP.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFTitrePKeyPressed
void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrech;
    private javax.swing.JTextField Domine;
    private com.toedter.calendar.JDateChooser Dt_ar;
    private com.toedter.calendar.JDateChooser Dt_dep;
    private javax.swing.JTextField TFIDprojet;
    private javax.swing.JTextField TFTitreP;
    private javax.swing.JTextField TFrech;
    private javax.swing.JLabel aa;
    private javax.swing.JLabel bb;
    private javax.swing.JPanel btnAjoutre;
    private javax.swing.JPanel btnImprime;
    private javax.swing.JPanel btnModifer;
    private javax.swing.JPanel btnSupprimer;
    private javax.swing.JPanel btnValide;
    private javax.swing.JButton duré;
    private javax.swing.JTextField duréaffiche;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIDprojet;
    private javax.swing.JLabel jLabelTitreP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
