/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratoirer;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static laboratoirer.equipes.cnx;
import net.proteanit.sql.DbUtils;
import java.sql.Statement;
/**
 *
 * @author PCexpress
 */
public class utilisationM extends javax.swing.JFrame {
      public static Connection cnx =DBConnexion.ConnectBD();
    PreparedStatement prepared=null;
    ResultSet resultat=null;
    int test=0;
    /**
     * Creates new form utilisationM
     */
    public utilisationM() {
        initComponents();
         setLocationRelativeTo(null);
          //ChekID();
        refresh();
    }
     public void refresh(){
    Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT * FROM `utilisermatériel` WHERE 1");
    ResultSet rs=pr.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException ex)
    {
    Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
    }
    }
    public void ChekID(){
      /*  Connection co=DBConnexion.ConnectBD();
    try{
    PreparedStatement pr=(PreparedStatement) co.prepareStatement("SELECT `Nom` FROM `utilisermatériel` WHERE 1");
    ResultSet rs=pr.executeQuery();
    while(rs.next()){
        String ID=rs.getString("Nom");
        String id=TFNommateriel.getText();
        if(ID.equals(id)){
            JOptionPane.showMessageDialog(null,"ce projet est dans les données");
            test=test+1;
        }else{
            
        }
    }
    }catch(SQLException e){
        e.printStackTrace();
    
    }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAjoutre = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btnModifer = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        btnImprime = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        btnvalide = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNumequi = new javax.swing.JLabel();
        jLabelQuant = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        TFNumequipe = new javax.swing.JTextField();
        TFQuantite = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TFrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        CBrech = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        btnAjoutre.setBackground(new java.awt.Color(64, 43, 100));
        btnAjoutre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjoutre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAjoutreMousePressed(evt);
            }
        });

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnAjoutreLayout = new javax.swing.GroupLayout(btnAjoutre);
        btnAjoutre.setLayout(btnAjoutreLayout);
        btnAjoutreLayout.setHorizontalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAjoutreLayout.setVerticalGroup(
            btnAjoutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAjoutreLayout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnModifer.setBackground(new java.awt.Color(64, 43, 100));
        btnModifer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifer.setPreferredSize(new java.awt.Dimension(110, 74));
        btnModifer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModiferMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModiferMousePressed(evt);
            }
        });

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnModiferLayout = new javax.swing.GroupLayout(btnModifer);
        btnModifer.setLayout(btnModiferLayout);
        btnModiferLayout.setHorizontalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnModiferLayout.setVerticalGroup(
            btnModiferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModiferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSupprimer.setBackground(new java.awt.Color(64, 43, 100));
        btnSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer.setPreferredSize(new java.awt.Dimension(110, 74));
        btnSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupprimerMousePressed(evt);
            }
        });

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupprimerLayout = new javax.swing.GroupLayout(btnSupprimer);
        btnSupprimer.setLayout(btnSupprimerLayout);
        btnSupprimerLayout.setHorizontalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        btnSupprimerLayout.setVerticalGroup(
            btnSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnImprime.setBackground(new java.awt.Color(64, 43, 100));
        btnImprime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprime.setPreferredSize(new java.awt.Dimension(110, 74));
        btnImprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimeMousePressed(evt);
            }
        });

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_print_55px.png"))); // NOI18N

        javax.swing.GroupLayout btnImprimeLayout = new javax.swing.GroupLayout(btnImprime);
        btnImprime.setLayout(btnImprimeLayout);
        btnImprimeLayout.setHorizontalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnImprimeLayout.setVerticalGroup(
            btnImprimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImprimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnvalide.setBackground(new java.awt.Color(64, 43, 100));
        btnvalide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvalide.setPreferredSize(new java.awt.Dimension(110, 74));
        btnvalide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvalideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnvalideMousePressed(evt);
            }
        });

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_view_55px_1.png"))); // NOI18N

        javax.swing.GroupLayout btnvalideLayout = new javax.swing.GroupLayout(btnvalide);
        btnvalide.setLayout(btnvalideLayout);
        btnvalideLayout.setHorizontalGroup(
            btnvalideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnvalideLayout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnvalideLayout.setVerticalGroup(
            btnvalideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnvalideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reply_all_arrow_55px.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAjoutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModifer, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(btnImprime, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(btnvalide, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjoutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnvalide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 558));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_g_50px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 31, 100));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 34, 33, 100));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 34, 32, 100));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 34, 27, 100));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 34, 14, 100));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 34, 26, 100));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 34, 30, 100));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_d_50px.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 34, 32, 100));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 34, 34, 100));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 34, 34, 100));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_u_50px.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 34, 33, 100));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 34, 26, 100));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 34, 15, 100));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_l_50px.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 34, 33, 100));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 34, 23, 100));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_s_50px.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 34, 34, 100));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_a_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 34, 35, 100));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 34, 28, 100));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 34, 14, 100));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_o_50px_6.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 34, 29, 100));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_n_50px.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 34, 31, 100));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_dishonored_50px.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 97, 27, 37));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_m_50px.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 34, 28, 100));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_a_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(881, 34, 27, 100));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_t_50px_2.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 34, 27, 100));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 34, 31, 100));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_r_50px_4.png"))); // NOI18N
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 34, 32, 100));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_i_50px_1.png"))); // NOI18N
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 34, 15, 100));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_e_50px.png"))); // NOI18N
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1043, 34, 29, 100));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Letters/icons8_l_50px.png"))); // NOI18N
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1078, 34, 27, 100));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_50px.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 80, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 1130, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89), 2));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNumequi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelNumequi.setText("Num équipe");

        jLabelQuant.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelQuant.setText("Quantité");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel33.setText("Nummatérial");

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        TFNumequipe.setBackground(new java.awt.Color(242, 242, 242));
        TFNumequipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNumequipeKeyPressed(evt);
            }
        });

        TFQuantite.setBackground(new java.awt.Color(242, 242, 242));
        TFQuantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFQuantiteActionPerformed(evt);
            }
        });
        TFQuantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFQuantiteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabelNumequi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TFNumequipe, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabelQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFNumequipe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNumequi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TFQuantite)
                        .addGap(34, 34, 34))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 1120, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 332, 1120, 220));

        TFrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFrechActionPerformed(evt);
            }
        });
        jPanel1.add(TFrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 380, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_50px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 90, 50));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel32.setText("recherche par catégoie:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, 50));

        CBrech.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CBrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NomMatériel", "Numéquipe", "Quantité" }));
        jPanel1.add(CBrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjoutreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMousePressed
        // TODO add your handling code here:
         setcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
         resetcolor(btnvalide);
    }//GEN-LAST:event_btnAjoutreMousePressed

    private void btnModiferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMousePressed
        // TODO add your handling code here:
        setcolor(btnModifer);
        resetcolor(btnAjoutre);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
         resetcolor(btnvalide);
    }//GEN-LAST:event_btnModiferMousePressed

    private void btnSupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMousePressed
        // TODO add your handling code here:
        setcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnImprime);
         resetcolor(btnvalide);
    }//GEN-LAST:event_btnSupprimerMousePressed

    private void btnImprimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMousePressed
        // TODO add your handling code here:
        setcolor(btnImprime);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnAjoutre);
        resetcolor(btnvalide);
    }//GEN-LAST:event_btnImprimeMousePressed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void btnvalideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalideMousePressed
        // TODO add your handling code here:
        setcolor(btnvalide);
        resetcolor(btnAjoutre);
        resetcolor(btnModifer);
        resetcolor(btnSupprimer);
        resetcolor(btnImprime);
    }//GEN-LAST:event_btnvalideMousePressed

    private void btnvalideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvalideMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        TFNumequipe.setText("");
        TFQuantite.setText("");
    }//GEN-LAST:event_btnvalideMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
         if(TFrech.getText().equals("")){
           
            JOptionPane.showMessageDialog(this, "SVP entrer quelque chose");
        }else 
            
            if(CBrech.getSelectedItem().equals("gkghkj")){
               try{
                    PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT `Nom`, `Quntité`, `Numequipe` FROM `utilisermatériel` WHERE `Quntité`="+TFrech.getText()+"");
                   
                    ResultSet rs=pr.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(SQLException ex)
                        {
                        Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                        }
                     }else 
                            if(CBrech.getSelectedItem().equals("NomMatériel")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `utilisermatériel` WHERE `Nom`=?");
                                 pr.setString(1, TFrech.getText());
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                }
                                else 
                            if(CBrech.getSelectedItem().equals("Numéquipe")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `utilisermatériel` WHERE `Numequipe`=?");
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                            }else 
                                 if(CBrech.getSelectedItem().equals("Quntité")){
                               try{
                                PreparedStatement pr=(PreparedStatement) cnx.prepareStatement("SELECT * FROM `utilisermatériel` WHERE `Quntité`=?");
                                ResultSet rs=pr.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                                }catch(SQLException ex)
                                {
                                Logger.getLogger(members.class.getName()).log(Level.SEVERE,null,ex);
                                }
                                         }
        
    
         



    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFrechActionPerformed

    private void btnAjoutreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutreMouseClicked
        // TODO add your handling code here:
        //ChekID(); 
        String NM=jTextField1.getText();
        String Q=TFQuantite.getText();
        String Né=TFNumequipe.getText();
        
        try {
        String sql="INSERT INTO `utilisermatériel`(`Nummatérial`, `Quantité`, `Numequipe`) VALUES (?,?,?)";
        
            prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, NM);
            prepared.setString(2, Q);
            prepared.setString(3, Né);
            prepared.execute();
            refresh();
            
          
          System.out.println("ajouter avec succès");
          }catch(Exception ex){
          System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnAjoutreMouseClicked

    private void btnModiferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiferMouseClicked
        // TODO add your handling code here:
         String NM=jTextField1.getText();
        String Q=TFQuantite.getText();
        String Né=TFNumequipe.getText();
         if (Q.equals("")||Né.equals(""))
        {
         JOptionPane.showMessageDialog(null,"champ vid","Error",JOptionPane.ERROR_MESSAGE);
        }
         String sql="UPDATE `utilisermatériel` SET `Quantité`=?"
                 + ",`Numequipe`=? WHERE  `Nummatérial`="+jTextField1.getText()+"";
        
        try{
        prepared =(PreparedStatement) Login.cnx.prepareStatement(sql);
            prepared.setString(1, Q);
            prepared.setString(2, Né);
            prepared.execute();
            refresh();
        }catch(SQLException e){
          System.out.println(e);
                  }
      


    }//GEN-LAST:event_btnModiferMouseClicked

    private void btnSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerMouseClicked
        // TODO add your handling code here:
        
   
      String NM=jTextField1.getText();
        try{
        String sql="DELETE FROM `utilisermatériel` WHERE `utilisermatériel`.`Nummatérial`= "+jTextField1.getText()+"";
       int cho  = JOptionPane.showConfirmDialog(null,"Êtes-vous sûr de vouloir supprimer");
       if(  cho == JOptionPane.YES_OPTION) {
           prepared=(PreparedStatement) Login.cnx.prepareStatement(sql);
           prepared.execute();
           System.out.println("Supprimer avec succès");
       } else {
       }
        refresh();
        
        }catch(Exception ex){
          System.out.println(ex);
        }
    }//GEN-LAST:event_btnSupprimerMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        jTextField1.setText(model.getValueAt(rowIndex, 0).toString());
        TFQuantite.setText(model.getValueAt(rowIndex, 1).toString());
        TFNumequipe.setText(model.getValueAt(rowIndex, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnImprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimeMouseClicked
        // TODO add your handling code here:
        String titer="liste des utilistionmaterial";
           impression.imprimerJtable(jTable1, titer);
    }//GEN-LAST:event_btnImprimeMouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
           changepassword CP = new changepassword();
                    CP.show();
                    dispose();                 

    }//GEN-LAST:event_jLabel34MouseClicked

    private void TFQuantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFQuantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFQuantiteActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {jTextField1.setEditable(false);
        jLabel33.setForeground(Color.red);
        }else{
            jTextField1.setEditable(true);
            jLabel33.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void TFNumequipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNumequipeKeyPressed
        // TODO add your handling code here:
           char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        {TFNumequipe.setEditable(false);
        jLabelNumequi.setForeground(Color.red);
        }else{
            TFNumequipe.setEditable(true);
            jLabelNumequi.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFNumequipeKeyPressed

    private void TFQuantiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFQuantiteKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c))
        { TFQuantite.setEditable(false);
        jLabelQuant.setForeground(Color.red);
        }else{
             TFQuantite.setEditable(true);
            jLabelQuant.setForeground(Color.black);
        }
    }//GEN-LAST:event_TFQuantiteKeyPressed
    void setcolor(JPanel panel)
    {
        panel.setBackground(new Color(85,65,118));
    }
    void resetcolor(JPanel panel)
    {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utilisationM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utilisationM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utilisationM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utilisationM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utilisationM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBrech;
    private javax.swing.JTextField TFNumequipe;
    private javax.swing.JTextField TFQuantite;
    private javax.swing.JTextField TFrech;
    private javax.swing.JPanel btnAjoutre;
    private javax.swing.JPanel btnImprime;
    private javax.swing.JPanel btnModifer;
    private javax.swing.JPanel btnSupprimer;
    private javax.swing.JPanel btnvalide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNumequi;
    private javax.swing.JLabel jLabelQuant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
